displayName=Unskulled Notifier
author=willzero123
description=Displays a reminder when you are unskulled, with option for revenant caves only
tags=skull,skulled,unskulled,notifier,reminder,notify,revs,revenant,revenants
plugins=com.unskullednotifier.UnskulledNotifierPlugin
