displayName=Unskulled Notifier
author=willzero123
description=Displays a "not skulled" icon overlay indicating that you are unskulled.
tags=skull,skulled,unskulled,notifier,reminder,notify,revs,revenant,revenants
plugins=com.unskullednotifier.UnskulledNotifierPlugin
